#!/bin/bash
chmod 777 0x01-python-if_else_loops_functions/*
git add 0x01-python-if_else_loops_functions
git commit -m "nnnnnnnnnnoooooooooooooo"
git reset 0x01-python-if_else_loops_functions/main.py
git push
